In [5]:
import pandas as pd

In [6]:
fornite_df=pd.read_csv("fornite.csv")

In [7]:
fornite_df

,Rarity,Weapon,DPS,Damage,Fire Rate,Magazine Size,Reload Time
0,Common,Assault Rifle,165.0,30.0,5.5,30,2.52
1,Uncommon,Assault Rifle,170.5,31.0,5.5,30,2.41
2,Rare,Assault Rifle,181.5,33.0,5.5,30,2.30
3,Epic,Assault Rifle,192.5,35.0,5.5,30,2.18
4,Legendary,Assault Rifle,198.0,36.0,5.5,30,2.07
...,...,...,...,...,...,...,...
264,Epic,Mechanical Shockwave Bow,89.0,89.0,1.0,1,1.00
265,Legendary,Mechanical Shockwave Bow,94.0,94.0,1.0,1,1.00
266,Epic,Mechanical Explosive Bow,89.0,89.0,1.0,1,1.00
267,Legendary,Mechanical Explosive Bow,94.0,94.0,1.0,1,1.00
268,Common,Harvesting Tool,32.0,20.0,1.6,0,0.00

In [8]:
fornite_df[(fornite_df['Rarity'] == 'Legendary') & (fornite_df['DPS'] >= 190)].head()

,Rarity,Weapon,DPS,Damage,Fire Rate,Magazine Size,Reload Time
4,Legendary,Assault Rifle,198.0,36.0,5.5,30,2.07
54,Legendary,Hammer Assault Rifle,191.4,33.0,5.8,20,1.98
72,Legendary,Primal Shotgun,250.8,66.0,3.8,12,3.40
101,Legendary,Double Barrel Shotgun,228.0,120.0,1.9,2,2.70
124,Legendary,Submachine Gun,200.0,20.0,10.0,35,1.89

In [9]:
max_daÃ±o = fornite_df['Damage'].max()
max_daÃ±o=fornite_df[fornite_df['Damage'] == max_daÃ±o]
max_daÃ±o

,Rarity,Weapon,DPS,Damage,Fire Rate,Magazine Size,Reload Time
90,Legendary,Dragonâ€™s Breath Shotgun,160.0,160.0,1.0,4,4.1

In [10]:
fornite_df[(fornite_df['Fire Rate'] >=5) & (fornite_df['Reload Time'] >= 2)].head()

,Rarity,Weapon,DPS,Damage,Fire Rate,Magazine Size,Reload Time
0,Common,Assault Rifle,165.0,30.0,5.5,30,2.52
1,Uncommon,Assault Rifle,170.5,31.0,5.5,30,2.41
2,Rare,Assault Rifle,181.5,33.0,5.5,30,2.30
3,Epic,Assault Rifle,192.5,35.0,5.5,30,2.18
4,Legendary,Assault Rifle,198.0,36.0,5.5,30,2.07

In [11]:
fornite_df[(fornite_df['Damage'] >=100) & (fornite_df['Damage'] <=120)].head()

,Rarity,Weapon,DPS,Damage,Fire Rate,Magazine Size,Reload Time
63,Rare,Pump Shotgun,70.0,102.0,0.70,5,4.40
64,Epic,Pump Shotgun,75.6,108.0,0.70,5,4.05
65,Legendary,Pump Shotgun,81.2,114.0,0.70,5,3.70
83,Legendary,Charge Shotgun,86.7,102.0,0.85,5,3.90
86,Rare,Lever Action Shotgun,98.3,103.5,0.95,6,6.00

In [12]:
fornite_df[(fornite_df['Weapon'] =='Pump Shotgun') & (fornite_df['Reload Time'] >=4.50)].head()

,Rarity,Weapon,DPS,Damage,Fire Rate,Magazine Size,Reload Time
61,Common,Pump Shotgun,58.8,91.0,0.7,5,5.10
62,Uncommon,Pump Shotgun,64.4,96.0,0.7,5,4.75